main: sk.DexterSK.FreeCoinFlip.CoinFlip
name: FreeCoinFlip
version: 1.9
description: Allow players to coinflip
author: DexterSK
api-version: 1.13
depend:
  - Vault
folia-supported: true
commands:
  coinflip:
    description: Opens coinflip menu
    aliases: cf