/*     */ package sk.DexterSK.FreeCoinFlip.utilz;
/*     */ 
/*     */ import java.util.Arrays;
/*     */ import java.util.HashMap;
/*     */ import java.util.Objects;
/*     */ import javax.annotation.Nonnull;
/*     */ import javax.annotation.Nullable;
/*     */ import org.apache.commons.lang.StringUtils;
/*     */ import org.apache.commons.lang.Validate;
/*     */ import org.bukkit.Sound;
/*     */ import org.bukkit.entity.Player;
/*     */ 
/*     */ public enum XSound {
/*  33 */   AMBIENT_CAVE(new String[] { "AMBIENCE_CAVE" }),
/*  34 */   AMBIENT_UNDERWATER_ENTER(new String[0]),
/*  35 */   AMBIENT_UNDERWATER_EXIT(new String[0]),
/*  36 */   AMBIENT_UNDERWATER_LOOP(new String[] { "AMBIENT_UNDERWATER_EXIT" }),
/*  37 */   AMBIENT_UNDERWATER_LOOP_ADDITIONS(new String[] { "AMBIENT_UNDERWATER_EXIT" }),
/*  38 */   AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE(new String[] { "AMBIENT_UNDERWATER_EXIT" }),
/*  39 */   AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE(new String[] { "AMBIENT_UNDERWATER_EXIT" }),
/*  40 */   BLOCK_ANVIL_BREAK(new String[] { "ANVIL_BREAK" }),
/*  41 */   BLOCK_ANVIL_DESTROY(new String[0]),
/*  42 */   BLOCK_ANVIL_FALL(new String[0]),
/*  43 */   BLOCK_ANVIL_HIT(new String[] { "BLOCK_ANVIL_FALL" }),
/*  44 */   BLOCK_ANVIL_LAND(new String[] { "ANVIL_LAND" }),
/*  45 */   BLOCK_ANVIL_PLACE(new String[] { "BLOCK_ANVIL_FALL" }),
/*  46 */   BLOCK_ANVIL_STEP(new String[] { "BLOCK_ANVIL_FALL" }),
/*  47 */   BLOCK_ANVIL_USE(new String[] { "ANVIL_USE" }),
/*  48 */   BLOCK_BEACON_ACTIVATE(new String[0]),
/*  49 */   BLOCK_BEACON_AMBIENT(new String[0]),
/*  50 */   BLOCK_BEACON_DEACTIVATE(new String[] { "BLOCK_BEACON_AMBIENT" }),
/*  51 */   BLOCK_BEACON_POWER_SELECT(new String[] { "BLOCK_BEACON_AMBIENT" }),
/*  52 */   BLOCK_BREWING_STAND_BREW(new String[0]),
/*  53 */   BLOCK_BUBBLE_COLUMN_BUBBLE_POP(new String[0]),
/*  54 */   BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT(new String[0]),
/*  55 */   BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE(new String[0]),
/*  56 */   BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT(new String[0]),
/*  57 */   BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE(new String[0]),
/*  58 */   BLOCK_CHEST_CLOSE(new String[] { "CHEST_CLOSE", "ENTITY_CHEST_CLOSE" }),
/*  59 */   BLOCK_CHEST_LOCKED(new String[0]),
/*  60 */   BLOCK_CHEST_OPEN(new String[] { "CHEST_OPEN", "ENTITY_CHEST_OPEN" }),
/*  61 */   BLOCK_CHORUS_FLOWER_DEATH(new String[0]),
/*  62 */   BLOCK_CHORUS_FLOWER_GROW(new String[0]),
/*  63 */   BLOCK_COMPARATOR_CLICK(new String[0]),
/*  64 */   BLOCK_CONDUIT_ACTIVATE(new String[0]),
/*  65 */   BLOCK_CONDUIT_AMBIENT(new String[0]),
/*  66 */   BLOCK_CONDUIT_AMBIENT_SHORT(new String[0]),
/*  67 */   BLOCK_CONDUIT_ATTACK_TARGET(new String[0]),
/*  68 */   BLOCK_CONDUIT_DEACTIVATE(new String[0]),
/*  69 */   BLOCK_CORAL_BLOCK_BREAK(new String[0]),
/*  70 */   BLOCK_CORAL_BLOCK_FALL(new String[0]),
/*  71 */   BLOCK_CORAL_BLOCK_HIT(new String[0]),
/*  72 */   BLOCK_CORAL_BLOCK_PLACE(new String[0]),
/*  73 */   BLOCK_CORAL_BLOCK_STEP(new String[0]),
/*  74 */   BLOCK_DISPENSER_DISPENSE(new String[0]),
/*  75 */   BLOCK_DISPENSER_FAIL(new String[0]),
/*  76 */   BLOCK_DISPENSER_LAUNCH(new String[0]),
/*  77 */   BLOCK_ENCHANTMENT_TABLE_USE(new String[0]),
/*  78 */   BLOCK_ENDER_CHEST_CLOSE(new String[0]),
/*  79 */   BLOCK_ENDER_CHEST_OPEN(new String[0]),
/*  80 */   BLOCK_END_GATEWAY_SPAWN(new String[0]),
/*  81 */   BLOCK_END_PORTAL_FRAME_FILL(new String[0]),
/*  82 */   BLOCK_END_PORTAL_SPAWN(new String[0]),
/*  83 */   BLOCK_FENCE_GATE_CLOSE(new String[0]),
/*  84 */   BLOCK_FENCE_GATE_OPEN(new String[0]),
/*  85 */   BLOCK_FIRE_AMBIENT(new String[] { "FIRE" }),
/*  86 */   BLOCK_FIRE_EXTINGUISH(new String[] { "FIZZ" }),
/*  87 */   BLOCK_FURNACE_FIRE_CRACKLE(new String[0]),
/*  88 */   BLOCK_GLASS_BREAK(new String[] { "GLASS" }),
/*  89 */   BLOCK_GLASS_FALL(new String[0]),
/*  90 */   BLOCK_GLASS_HIT(new String[0]),
/*  91 */   BLOCK_GLASS_PLACE(new String[0]),
/*  92 */   BLOCK_GLASS_STEP(new String[0]),
/*  93 */   BLOCK_GRASS_BREAK(new String[] { "DIG_GRASS" }),
/*  94 */   BLOCK_GRASS_FALL(new String[0]),
/*  95 */   BLOCK_GRASS_HIT(new String[0]),
/*  96 */   BLOCK_GRASS_PLACE(new String[0]),
/*  97 */   BLOCK_GRASS_STEP(new String[] { "STEP_GRASS" }),
/*  98 */   BLOCK_GRAVEL_BREAK(new String[] { "DIG_GRAVEL" }),
/*  99 */   BLOCK_GRAVEL_FALL(new String[0]),
/* 100 */   BLOCK_GRAVEL_HIT(new String[0]),
/* 101 */   BLOCK_GRAVEL_PLACE(new String[0]),
/* 102 */   BLOCK_GRAVEL_STEP(new String[] { "STEP_GRAVEL" }),
/* 103 */   BLOCK_IRON_DOOR_CLOSE(new String[0]),
/* 104 */   BLOCK_IRON_DOOR_OPEN(new String[0]),
/* 105 */   BLOCK_IRON_TRAPDOOR_CLOSE(new String[0]),
/* 106 */   BLOCK_IRON_TRAPDOOR_OPEN(new String[0]),
/* 107 */   BLOCK_LADDER_BREAK(new String[0]),
/* 108 */   BLOCK_LADDER_FALL(new String[0]),
/* 109 */   BLOCK_LADDER_HIT(new String[0]),
/* 110 */   BLOCK_LADDER_PLACE(new String[0]),
/* 111 */   BLOCK_LADDER_STEP(new String[] { "STEP_LADDER" }),
/* 112 */   BLOCK_LAVA_AMBIENT(new String[] { "LAVA" }),
/* 113 */   BLOCK_LAVA_EXTINGUISH(new String[0]),
/* 114 */   BLOCK_LAVA_POP(new String[] { "LAVA_POP" }),
/* 115 */   BLOCK_LEVER_CLICK(new String[0]),
/* 116 */   BLOCK_LILY_PAD_PLACE(new String[] { "BLOCK_WATERLILY_PLACE" }),
/* 117 */   BLOCK_METAL_BREAK(new String[0]),
/* 118 */   BLOCK_METAL_FALL(new String[0]),
/* 119 */   BLOCK_METAL_HIT(new String[0]),
/* 120 */   BLOCK_METAL_PLACE(new String[0]),
/* 121 */   BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF(new String[] { "BLOCK_METAL_PRESSUREPLATE_CLICK_OFF" }),
/* 122 */   BLOCK_METAL_PRESSURE_PLATE_CLICK_ON(new String[] { "BLOCK_METAL_PRESSUREPLATE_CLICK_ON" }),
/* 123 */   BLOCK_METAL_STEP(new String[0]),
/* 124 */   BLOCK_NOTE_BLOCK_BASEDRUM(new String[] { "NOTE_BASS_DRUM", "BLOCK_NOTE_BASEDRUM" }),
/* 125 */   BLOCK_NOTE_BLOCK_BASS(new String[] { "NOTE_BASS", "BLOCK_NOTE_BASS" }),
/* 126 */   BLOCK_NOTE_BLOCK_BELL(new String[0]),
/* 127 */   BLOCK_NOTE_BLOCK_CHIME(new String[0]),
/* 128 */   BLOCK_NOTE_BLOCK_FLUTE(new String[0]),
/* 129 */   BLOCK_NOTE_BLOCK_GUITAR(new String[] { "NOTE_BASS_GUITAR", "BLOCK_NOTE_GUITAR", "BLOCK_NOTE_BASS" }),
/* 130 */   BLOCK_NOTE_BLOCK_HARP(new String[] { "NOTE_PIANO", "BLOCK_NOTE_HARP" }),
/* 131 */   BLOCK_NOTE_BLOCK_HAT(new String[] { "NOTE_STICKS", "BLOCK_NOTE_HAT" }),
/* 132 */   BLOCK_NOTE_BLOCK_PLING(new String[] { "NOTE_PLING", "BLOCK_NOTE_PLING" }),
/* 133 */   BLOCK_NOTE_BLOCK_SNARE(new String[] { "NOTE_SNARE_DRUM", "BLOCK_NOTE_SNARE" }),
/* 134 */   BLOCK_NOTE_BLOCK_XYLOPHONE(new String[] { "BLOCK_NOTE_XYLOPHONE" }),
/* 135 */   BLOCK_PISTON_CONTRACT(new String[] { "PISTON_RETRACT" }),
/* 136 */   BLOCK_PISTON_EXTEND(new String[] { "PISTON_EXTEND" }),
/* 137 */   BLOCK_PORTAL_AMBIENT(new String[] { "PORTAL" }),
/* 138 */   BLOCK_PORTAL_TRAVEL(new String[] { "PORTAL_TRAVEL" }),
/* 139 */   BLOCK_PORTAL_TRIGGER(new String[] { "PORTAL_TRIGGER" }),
/* 140 */   BLOCK_PUMPKIN_CARVE(new String[0]),
/* 141 */   BLOCK_REDSTONE_TORCH_BURNOUT(new String[0]),
/* 142 */   BLOCK_SAND_BREAK(new String[] { "DIG_SAND" }),
/* 143 */   BLOCK_SAND_FALL(new String[0]),
/* 144 */   BLOCK_SAND_HIT(new String[0]),
/* 145 */   BLOCK_SAND_PLACE(new String[0]),
/* 146 */   BLOCK_SAND_STEP(new String[] { "STEP_SAND" }),
/* 147 */   BLOCK_SHULKER_BOX_CLOSE(new String[0]),
/* 148 */   BLOCK_SHULKER_BOX_OPEN(new String[0]),
/* 149 */   BLOCK_SLIME_BLOCK_BREAK(new String[] { "BLOCK_SLIME_BREAK" }),
/* 150 */   BLOCK_SLIME_BLOCK_FALL(new String[] { "BLOCK_SLIME_FALL" }),
/* 151 */   BLOCK_SLIME_BLOCK_HIT(new String[] { "BLOCK_SLIME_HIT" }),
/* 152 */   BLOCK_SLIME_BLOCK_PLACE(new String[] { "BLOCK_SLIME_PLACE" }),
/* 153 */   BLOCK_SLIME_BLOCK_STEP(new String[] { "BLOCK_SLIME_STEP" }),
/* 154 */   BLOCK_SNOW_BREAK(new String[] { "DIG_SNOW" }),
/* 155 */   BLOCK_SNOW_FALL(new String[0]),
/* 156 */   BLOCK_SNOW_HIT(new String[0]),
/* 157 */   BLOCK_SNOW_PLACE(new String[0]),
/* 158 */   BLOCK_SNOW_STEP(new String[] { "STEP_SNOW" }),
/* 159 */   BLOCK_STONE_BREAK(new String[] { "DIG_STONE" }),
/* 160 */   BLOCK_STONE_BUTTON_CLICK_OFF(new String[0]),
/* 161 */   BLOCK_STONE_BUTTON_CLICK_ON(new String[0]),
/* 162 */   BLOCK_STONE_FALL(new String[0]),
/* 163 */   BLOCK_STONE_HIT(new String[0]),
/* 164 */   BLOCK_STONE_PLACE(new String[0]),
/* 165 */   BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF(new String[] { "BLOCK_STONE_PRESSUREPLATE_CLICK_OFF" }),
/* 166 */   BLOCK_STONE_PRESSURE_PLATE_CLICK_ON(new String[] { "BLOCK_STONE_PRESSUREPLATE_CLICK_ON" }),
/* 167 */   BLOCK_STONE_STEP(new String[] { "STEP_STONE" }),
/* 168 */   BLOCK_TRIPWIRE_ATTACH(new String[0]),
/* 169 */   BLOCK_TRIPWIRE_CLICK_OFF(new String[0]),
/* 170 */   BLOCK_TRIPWIRE_CLICK_ON(new String[0]),
/* 171 */   BLOCK_TRIPWIRE_DETACH(new String[0]),
/* 172 */   BLOCK_WATER_AMBIENT(new String[] { "WATER" }),
/* 173 */   BLOCK_WET_GRASS_BREAK(new String[0]),
/* 174 */   BLOCK_WET_GRASS_FALL(new String[0]),
/* 175 */   BLOCK_WET_GRASS_HIT(new String[0]),
/* 176 */   BLOCK_WET_GRASS_PLACE(new String[] { "BLOCK_WET_GRASS_HIT" }),
/* 177 */   BLOCK_WET_GRASS_STEP(new String[] { "BLOCK_WET_GRASS_HIT" }),
/* 178 */   BLOCK_WOODEN_BUTTON_CLICK_OFF(new String[] { "WOOD_CLICK", "BLOCK_WOOD_BUTTON_CLICK_OFF" }),
/* 179 */   BLOCK_WOODEN_BUTTON_CLICK_ON(new String[] { "WOOD_CLICK", "BLOCK_WOOD_BUTTON_CLICK_ON" }),
/* 180 */   BLOCK_WOODEN_DOOR_CLOSE(new String[] { "DOOR_CLOSE" }),
/* 181 */   BLOCK_WOODEN_DOOR_OPEN(new String[] { "DOOR_OPEN" }),
/* 182 */   BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF(new String[] { "BLOCK_WOOD_PRESSUREPLATE_CLICK_OFF" }),
/* 183 */   BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON(new String[] { "BLOCK_WOOD_PRESSUREPLATE_CLICK_ON" }),
/* 184 */   BLOCK_WOODEN_TRAPDOOR_CLOSE(new String[0]),
/* 185 */   BLOCK_WOODEN_TRAPDOOR_OPEN(new String[0]),
/* 186 */   BLOCK_WOOD_BREAK(new String[] { "DIG_WOOD" }),
/* 187 */   BLOCK_WOOD_FALL(new String[0]),
/* 188 */   BLOCK_WOOD_HIT(new String[0]),
/* 189 */   BLOCK_WOOD_PLACE(new String[0]),
/* 190 */   BLOCK_WOOD_STEP(new String[] { "STEP_WOOD" }),
/* 191 */   BLOCK_WOOL_BREAK(new String[] { "DIG_WOOL", "BLOCK_CLOTH_BREAK" }),
/* 192 */   BLOCK_WOOL_FALL(new String[0]),
/* 193 */   BLOCK_WOOL_HIT(new String[] { "BLOCK_WOOL_FALL" }),
/* 194 */   BLOCK_WOOL_PLACE(new String[] { "BLOCK_WOOL_FALL" }),
/* 195 */   BLOCK_WOOL_STEP(new String[] { "STEP_WOOL", "BLOCK_CLOTH_STEP" }),
/* 196 */   ENCHANT_THORNS_HIT(new String[0]),
/* 197 */   ENTITY_ARMOR_STAND_BREAK(new String[] { "ENTITY_ARMORSTAND_BREAK" }),
/* 198 */   ENTITY_ARMOR_STAND_FALL(new String[] { "ENTITY_ARMORSTAND_FALL" }),
/* 199 */   ENTITY_ARMOR_STAND_HIT(new String[] { "ENTITY_ARMORSTAND_HIT" }),
/* 200 */   ENTITY_ARMOR_STAND_PLACE(new String[] { "ENTITY_ARMORSTAND_PLACE" }),
/* 201 */   ENTITY_ARROW_HIT(new String[] { "ARROW_HIT" }),
/* 202 */   ENTITY_ARROW_HIT_PLAYER(new String[0]),
/* 203 */   ENTITY_ARROW_SHOOT(new String[] { "SHOOT_ARROW" }),
/* 204 */   ENTITY_BAT_AMBIENT(new String[] { "BAT_IDLE" }),
/* 205 */   ENTITY_BAT_DEATH(new String[] { "BAT_DEATH" }),
/* 206 */   ENTITY_BAT_HURT(new String[] { "BAT_HURT" }),
/* 207 */   ENTITY_BAT_LOOP(new String[] { "BAT_LOOP" }),
/* 208 */   ENTITY_BAT_TAKEOFF(new String[] { "BAT_TAKEOFF" }),
/* 209 */   ENTITY_BLAZE_AMBIENT(new String[] { "BLAZE_BREATH" }),
/* 210 */   ENTITY_BLAZE_BURN(new String[0]),
/* 211 */   ENTITY_BLAZE_DEATH(new String[] { "BLAZE_DEATH" }),
/* 212 */   ENTITY_BLAZE_HURT(new String[] { "BLAZE_HIT" }),
/* 213 */   ENTITY_BLAZE_SHOOT(new String[0]),
/* 214 */   ENTITY_BOAT_PADDLE_LAND(new String[0]),
/* 215 */   ENTITY_BOAT_PADDLE_WATER(new String[0]),
/* 216 */   ENTITY_CAT_AMBIENT(new String[] { "CAT_MEOW" }),
/* 217 */   ENTITY_CAT_DEATH(new String[0]),
/* 218 */   ENTITY_CAT_HISS(new String[] { "CAT_HISS" }),
/* 219 */   ENTITY_CAT_HURT(new String[] { "CAT_HIT" }),
/* 220 */   ENTITY_CAT_PURR(new String[] { "CAT_PURR" }),
/* 221 */   ENTITY_CAT_PURREOW(new String[] { "CAT_PURREOW" }),
/* 222 */   ENTITY_CHICKEN_AMBIENT(new String[] { "CHICKEN_IDLE" }),
/* 223 */   ENTITY_CHICKEN_DEATH(new String[0]),
/* 224 */   ENTITY_CHICKEN_EGG(new String[] { "CHICKEN_EGG_POP" }),
/* 225 */   ENTITY_CHICKEN_HURT(new String[] { "CHICKEN_HURT" }),
/* 226 */   ENTITY_CHICKEN_STEP(new String[] { "CHICKEN_WALK" }),
/* 227 */   ENTITY_COD_AMBIENT(new String[0]),
/* 228 */   ENTITY_COD_DEATH(new String[0]),
/* 229 */   ENTITY_COD_FLOP(new String[0]),
/* 230 */   ENTITY_COD_HURT(new String[0]),
/* 231 */   ENTITY_COW_AMBIENT(new String[] { "COW_IDLE" }),
/* 232 */   ENTITY_COW_DEATH(new String[0]),
/* 233 */   ENTITY_COW_HURT(new String[] { "COW_HURT" }),
/* 234 */   ENTITY_COW_MILK(new String[0]),
/* 235 */   ENTITY_COW_STEP(new String[] { "COW_WALK" }),
/* 236 */   ENTITY_CREEPER_DEATH(new String[] { "CREEPER_DEATH" }),
/* 237 */   ENTITY_CREEPER_HURT(new String[0]),
/* 238 */   ENTITY_CREEPER_PRIMED(new String[] { "CREEPER_HISS" }),
/* 239 */   ENTITY_DOLPHIN_AMBIENT(new String[0]),
/* 240 */   ENTITY_DOLPHIN_AMBIENT_WATER(new String[0]),
/* 241 */   ENTITY_DOLPHIN_ATTACK(new String[0]),
/* 242 */   ENTITY_DOLPHIN_DEATH(new String[0]),
/* 243 */   ENTITY_DOLPHIN_EAT(new String[0]),
/* 244 */   ENTITY_DOLPHIN_HURT(new String[0]),
/* 245 */   ENTITY_DOLPHIN_JUMP(new String[0]),
/* 246 */   ENTITY_DOLPHIN_PLAY(new String[0]),
/* 247 */   ENTITY_DOLPHIN_SPLASH(new String[0]),
/* 248 */   ENTITY_DOLPHIN_SWIM(new String[0]),
/* 249 */   ENTITY_DONKEY_AMBIENT(new String[] { "DONKEY_IDLE" }),
/* 250 */   ENTITY_DONKEY_ANGRY(new String[] { "DONKEY_ANGRY" }),
/* 251 */   ENTITY_DONKEY_CHEST(new String[0]),
/* 252 */   ENTITY_DONKEY_DEATH(new String[] { "DONKEY_DEATH" }),
/* 253 */   ENTITY_DONKEY_HURT(new String[] { "DONKEY_HIT" }),
/* 254 */   ENTITY_DRAGON_FIREBALL_EXPLODE(new String[] { "ENTITY_ENDERDRAGON_FIREBALL_EXPLODE" }),
/* 255 */   ENTITY_DROWNED_AMBIENT(new String[0]),
/* 256 */   ENTITY_DROWNED_AMBIENT_WATER(new String[0]),
/* 257 */   ENTITY_DROWNED_DEATH(new String[0]),
/* 258 */   ENTITY_DROWNED_DEATH_WATER(new String[0]),
/* 259 */   ENTITY_DROWNED_HURT(new String[0]),
/* 260 */   ENTITY_DROWNED_HURT_WATER(new String[0]),
/* 261 */   ENTITY_DROWNED_SHOOT(new String[0]),
/* 262 */   ENTITY_DROWNED_STEP(new String[0]),
/* 263 */   ENTITY_DROWNED_SWIM(new String[0]),
/* 264 */   ENTITY_EGG_THROW(new String[0]),
/* 265 */   ENTITY_ELDER_GUARDIAN_AMBIENT(new String[0]),
/* 266 */   ENTITY_ELDER_GUARDIAN_AMBIENT_LAND(new String[0]),
/* 267 */   ENTITY_ELDER_GUARDIAN_CURSE(new String[0]),
/* 268 */   ENTITY_ELDER_GUARDIAN_DEATH(new String[0]),
/* 269 */   ENTITY_ELDER_GUARDIAN_DEATH_LAND(new String[0]),
/* 270 */   ENTITY_ELDER_GUARDIAN_FLOP(new String[0]),
/* 271 */   ENTITY_ELDER_GUARDIAN_HURT(new String[0]),
/* 272 */   ENTITY_ELDER_GUARDIAN_HURT_LAND(new String[0]),
/* 273 */   ENTITY_ENDERMAN_AMBIENT(new String[] { "ENDERMAN_IDLE", "ENTITY_ENDERMEN_AMBIENT" }),
/* 274 */   ENTITY_ENDERMAN_DEATH(new String[] { "ENDERMAN_DEATH", "ENTITY_ENDERMEN_DEATH" }),
/* 275 */   ENTITY_ENDERMAN_HURT(new String[] { "ENDERMAN_HIT", "ENTITY_ENDERMEN_HURT" }),
/* 276 */   ENTITY_ENDERMAN_SCREAM(new String[] { "ENDERMAN_SCREAM", "ENTITY_ENDERMEN_SCREAM" }),
/* 277 */   ENTITY_ENDERMAN_STARE(new String[] { "ENDERMAN_STARE", "ENTITY_ENDERMEN_STARE" }),
/* 278 */   ENTITY_ENDERMAN_TELEPORT(new String[] { "ENDERMAN_TELEPORT", "ENTITY_ENDERMEN_TELEPORT" }),
/* 279 */   ENTITY_ENDERMITE_AMBIENT(new String[0]),
/* 280 */   ENTITY_ENDERMITE_DEATH(new String[0]),
/* 281 */   ENTITY_ENDERMITE_HURT(new String[0]),
/* 282 */   ENTITY_ENDERMITE_STEP(new String[0]),
/* 283 */   ENTITY_ENDER_DRAGON_AMBIENT(new String[] { "ENDERDRAGON_WINGS", "ENTITY_ENDERDRAGON_AMBIENT" }),
/* 284 */   ENTITY_ENDER_DRAGON_DEATH(new String[] { "ENDERDRAGON_DEATH", "ENTITY_ENDERDRAGON_DEATH" }),
/* 285 */   ENTITY_ENDER_DRAGON_FLAP(new String[] { "ENDERDRAGON_WINGS", "ENTITY_ENDERDRAGON_FLAP" }),
/* 286 */   ENTITY_ENDER_DRAGON_GROWL(new String[] { "ENDERDRAGON_GROWL", "ENTITY_ENDERDRAGON_GROWL" }),
/* 287 */   ENTITY_ENDER_DRAGON_HURT(new String[] { "ENDERDRAGON_HIT", "ENTITY_ENDERDRAGON_HURT" }),
/* 288 */   ENTITY_ENDER_DRAGON_SHOOT(new String[] { "ENTITY_ENDERDRAGON_SHOOT" }),
/* 289 */   ENTITY_ENDER_EYE_DEATH(new String[0]),
/* 290 */   ENTITY_ENDER_EYE_LAUNCH(new String[] { "ENTITY_ENDER_EYE_DEATH", "ENTITY_ENDEREYE_DEATH" }),
/* 291 */   ENTITY_ENDER_PEARL_THROW(new String[] { "ENTITY_ENDERPEARL_THROW" }),
/* 292 */   ENTITY_EVOKER_AMBIENT(new String[] { "ENTITY_EVOCATION_ILLAGER_AMBIENT" }),
/* 293 */   ENTITY_EVOKER_CAST_SPELL(new String[] { "ENTITY_EVOCATION_ILLAGER_CAST_SPELL" }),
/* 294 */   ENTITY_EVOKER_DEATH(new String[] { "ENTITY_EVOCATION_ILLAGER_DEATH" }),
/* 295 */   ENTITY_EVOKER_FANGS_ATTACK(new String[] { "ENTITY_EVOCATION_FANGS_ATTACK" }),
/* 296 */   ENTITY_EVOKER_HURT(new String[] { "ENTITY_EVOCATION_ILLAGER_HURT" }),
/* 297 */   ENTITY_EVOKER_PREPARE_ATTACK(new String[] { "ENTITY_EVOCATION_ILLAGER_PREPARE_ATTACK" }),
/* 298 */   ENTITY_EVOKER_PREPARE_SUMMON(new String[] { "ENTITY_EVOCATION_ILLAGER_PREPARE_SUMMON" }),
/* 299 */   ENTITY_EVOKER_PREPARE_WOLOLO(new String[] { "ENTITY_EVOCATION_ILLAGER_PREPARE_WOLOLO" }),
/* 300 */   ENTITY_EXPERIENCE_BOTTLE_THROW(new String[0]),
/* 301 */   ENTITY_EXPERIENCE_ORB_PICKUP(new String[] { "ORB_PICKUP" }),
/* 302 */   ENTITY_FIREWORK_ROCKET_BLAST(new String[] { "FIREWORK_BLAST", "ENTITY_FIREWORK_BLAST" }),
/* 303 */   ENTITY_FIREWORK_ROCKET_BLAST_FAR(new String[] { "FIREWORK_BLAST2", "ENTITY_FIREWORK_BLAST_FAR" }),
/* 304 */   ENTITY_FIREWORK_ROCKET_LARGE_BLAST(new String[] { "FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_LARGE_BLAST" }),
/* 305 */   ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR(new String[] { "FIREWORK_LARGE_BLAST2", "ENTITY_FIREWORK_LARGE_BLAST_FAR" }),
/* 306 */   ENTITY_FIREWORK_ROCKET_LAUNCH(new String[] { "FIREWORK_LAUNCH", "ENTITY_FIREWORK_LAUNCH" }),
/* 307 */   ENTITY_FIREWORK_ROCKET_SHOOT(new String[0]),
/* 308 */   ENTITY_FIREWORK_ROCKET_TWINKLE(new String[] { "FIREWORK_TWINKLE", "ENTITY_FIREWORK_TWINKLE" }),
/* 309 */   ENTITY_FIREWORK_ROCKET_TWINKLE_FAR(new String[] { "FIREWORK_TWINKLE2", "ENTITY_FIREWORK_TWINKLE_FAR" }),
/* 310 */   ENTITY_FISHING_BOBBER_RETRIEVE(new String[0]),
/* 311 */   ENTITY_FISHING_BOBBER_SPLASH(new String[] { "SPLASH2", "ENTITY_BOBBER_SPLASH" }),
/* 312 */   ENTITY_FISHING_BOBBER_THROW(new String[] { "ENTITY_BOBBER_THROW" }),
/* 313 */   ENTITY_FISH_SWIM(new String[0]),
/* 314 */   ENTITY_GENERIC_BIG_FALL(new String[] { "FALL_BIG" }),
/* 315 */   ENTITY_GENERIC_BURN(new String[0]),
/* 316 */   ENTITY_GENERIC_DEATH(new String[0]),
/* 317 */   ENTITY_GENERIC_DRINK(new String[] { "DRINK" }),
/* 318 */   ENTITY_GENERIC_EAT(new String[] { "EAT" }),
/* 319 */   ENTITY_GENERIC_EXPLODE(new String[] { "EXPLODE" }),
/* 320 */   ENTITY_GENERIC_EXTINGUISH_FIRE(new String[0]),
/* 321 */   ENTITY_GENERIC_HURT(new String[0]),
/* 322 */   ENTITY_GENERIC_SMALL_FALL(new String[] { "FALL_SMALL" }),
/* 323 */   ENTITY_GENERIC_SPLASH(new String[] { "SPLASH" }),
/* 324 */   ENTITY_GENERIC_SWIM(new String[] { "SWIM" }),
/* 325 */   ENTITY_GHAST_AMBIENT(new String[] { "GHAST_MOAN" }),
/* 326 */   ENTITY_GHAST_DEATH(new String[] { "GHAST_DEATH" }),
/* 327 */   ENTITY_GHAST_HURT(new String[] { "GHAST_SCREAM2" }),
/* 328 */   ENTITY_GHAST_SCREAM(new String[] { "GHAST_SCREAM" }),
/* 329 */   ENTITY_GHAST_SHOOT(new String[] { "GHAST_FIREBALL" }),
/* 330 */   ENTITY_GHAST_WARN(new String[] { "GHAST_CHARGE" }),
/* 331 */   ENTITY_GUARDIAN_AMBIENT(new String[0]),
/* 332 */   ENTITY_GUARDIAN_AMBIENT_LAND(new String[0]),
/* 333 */   ENTITY_GUARDIAN_ATTACK(new String[0]),
/* 334 */   ENTITY_GUARDIAN_DEATH(new String[0]),
/* 335 */   ENTITY_GUARDIAN_DEATH_LAND(new String[0]),
/* 336 */   ENTITY_GUARDIAN_FLOP(new String[0]),
/* 337 */   ENTITY_GUARDIAN_HURT(new String[0]),
/* 338 */   ENTITY_GUARDIAN_HURT_LAND(new String[0]),
/* 339 */   ENTITY_HORSE_AMBIENT(new String[] { "HORSE_IDLE" }),
/* 340 */   ENTITY_HORSE_ANGRY(new String[] { "HORSE_ANGRY" }),
/* 341 */   ENTITY_HORSE_ARMOR(new String[] { "HORSE_ARMOR" }),
/* 342 */   ENTITY_HORSE_BREATHE(new String[] { "HORSE_BREATHE" }),
/* 343 */   ENTITY_HORSE_DEATH(new String[] { "HORSE_DEATH" }),
/* 344 */   ENTITY_HORSE_EAT(new String[0]),
/* 345 */   ENTITY_HORSE_GALLOP(new String[] { "HORSE_GALLOP" }),
/* 346 */   ENTITY_HORSE_HURT(new String[] { "HORSE_HIT" }),
/* 347 */   ENTITY_HORSE_JUMP(new String[] { "HORSE_JUMP" }),
/* 348 */   ENTITY_HORSE_LAND(new String[] { "HORSE_LAND" }),
/* 349 */   ENTITY_HORSE_SADDLE(new String[] { "HORSE_SADDLE" }),
/* 350 */   ENTITY_HORSE_STEP(new String[] { "HORSE_SOFT" }),
/* 351 */   ENTITY_HORSE_STEP_WOOD(new String[] { "HORSE_WOOD" }),
/* 352 */   ENTITY_HOSTILE_BIG_FALL(new String[] { "FALL_BIG" }),
/* 353 */   ENTITY_HOSTILE_DEATH(new String[0]),
/* 354 */   ENTITY_HOSTILE_HURT(new String[0]),
/* 355 */   ENTITY_HOSTILE_SMALL_FALL(new String[] { "FALL_SMALL" }),
/* 356 */   ENTITY_HOSTILE_SPLASH(new String[] { "SPLASH" }),
/* 357 */   ENTITY_HOSTILE_SWIM(new String[] { "SWIM" }),
/* 358 */   ENTITY_HUSK_AMBIENT(new String[0]),
/* 359 */   ENTITY_HUSK_CONVERTED_TO_ZOMBIE(new String[0]),
/* 360 */   ENTITY_HUSK_DEATH(new String[0]),
/* 361 */   ENTITY_HUSK_HURT(new String[0]),
/* 362 */   ENTITY_HUSK_STEP(new String[0]),
/* 363 */   ENTITY_ILLUSIONER_AMBIENT(new String[] { "ENTITY_ILLUSION_ILLAGER_AMBIENT" }),
/* 364 */   ENTITY_ILLUSIONER_CAST_SPELL(new String[] { "ENTITY_ILLUSION_ILLAGER_CAST_SPELL" }),
/* 365 */   ENTITY_ILLUSIONER_DEATH(new String[] { "ENTITY_ILLUSIONER_CAST_DEATH", "ENTITY_ILLUSION_ILLAGER_DEATH" }),
/* 366 */   ENTITY_ILLUSIONER_HURT(new String[] { "ENTITY_ILLUSION_ILLAGER_HURT" }),
/* 367 */   ENTITY_ILLUSIONER_MIRROR_MOVE(new String[] { "ENTITY_ILLUSION_ILLAGER_MIRROR_MOVE" }),
/* 368 */   ENTITY_ILLUSIONER_PREPARE_BLINDNESS(new String[] { "ENTITY_ILLUSION_ILLAGER_PREPARE_BLINDNESS" }),
/* 369 */   ENTITY_ILLUSIONER_PREPARE_MIRROR(new String[] { "ENTITY_ILLUSION_ILLAGER_PREPARE_MIRROR" }),
/* 370 */   ENTITY_IRON_GOLEM_ATTACK(new String[] { "IRONGOLEM_THROW", "ENTITY_IRONGOLEM_ATTACK" }),
/* 371 */   ENTITY_IRON_GOLEM_DEATH(new String[] { "IRONGOLEM_DEATH", "ENTITY_IRONGOLEM_DEATH" }),
/* 372 */   ENTITY_IRON_GOLEM_HURT(new String[] { "IRONGOLEM_HIT", "ENTITY_IRONGOLEM_HURT" }),
/* 373 */   ENTITY_IRON_GOLEM_STEP(new String[] { "IRONGOLEM_WALK", "ENTITY_IRONGOLEM_STEP" }),
/* 374 */   ENTITY_ITEM_BREAK(new String[] { "ITEM_BREAK" }),
/* 375 */   ENTITY_ITEM_FRAME_ADD_ITEM(new String[] { "ENTITY_ITEMFRAME_ADD_ITEM" }),
/* 376 */   ENTITY_ITEM_FRAME_BREAK(new String[] { "ENTITY_ITEMFRAME_BREAK" }),
/* 377 */   ENTITY_ITEM_FRAME_PLACE(new String[] { "ENTITY_ITEMFRAME_PLACE" }),
/* 378 */   ENTITY_ITEM_FRAME_REMOVE_ITEM(new String[] { "ENTITY_ITEMFRAME_REMOVE_ITEM" }),
/* 379 */   ENTITY_ITEM_FRAME_ROTATE_ITEM(new String[] { "ENTITY_ITEMFRAME_ROTATE_ITEM" }),
/* 380 */   ENTITY_ITEM_PICKUP(new String[] { "ITEM_PICKUP" }),
/* 381 */   ENTITY_LEASH_KNOT_BREAK(new String[] { "ENTITY_LEASHKNOT_BREAK" }),
/* 382 */   ENTITY_LEASH_KNOT_PLACE(new String[] { "ENTITY_LEASHKNOT_PLACE" }),
/* 383 */   ENTITY_LIGHTNING_BOLT_IMPACT(new String[] { "AMBIENCE_THUNDER", "ENTITY_LIGHTNING_IMPACT" }),
/* 384 */   ENTITY_LIGHTNING_BOLT_THUNDER(new String[] { "AMBIENCE_THUNDER", "ENTITY_LIGHTNING_THUNDER" }),
/* 385 */   ENTITY_LINGERING_POTION_THROW(new String[0]),
/* 386 */   ENTITY_LLAMA_AMBIENT(new String[0]),
/* 387 */   ENTITY_LLAMA_ANGRY(new String[0]),
/* 388 */   ENTITY_LLAMA_CHEST(new String[0]),
/* 389 */   ENTITY_LLAMA_DEATH(new String[0]),
/* 390 */   ENTITY_LLAMA_EAT(new String[0]),
/* 391 */   ENTITY_LLAMA_HURT(new String[0]),
/* 392 */   ENTITY_LLAMA_SPIT(new String[0]),
/* 393 */   ENTITY_LLAMA_STEP(new String[0]),
/* 394 */   ENTITY_LLAMA_SWAG(new String[0]),
/* 395 */   ENTITY_MAGMA_CUBE_DEATH(new String[] { "ENTITY_MAGMACUBE_DEATH" }),
/* 396 */   ENTITY_MAGMA_CUBE_DEATH_SMALL(new String[] { "ENTITY_SMALL_MAGMACUBE_DEATH" }),
/* 397 */   ENTITY_MAGMA_CUBE_HURT(new String[] { "ENTITY_MAGMACUBE_HURT" }),
/* 398 */   ENTITY_MAGMA_CUBE_HURT_SMALL(new String[] { "ENTITY_SMALL_MAGMACUBE_HURT" }),
/* 399 */   ENTITY_MAGMA_CUBE_JUMP(new String[] { "MAGMACUBE_JUMP", "ENTITY_MAGMACUBE_JUMP" }),
/* 400 */   ENTITY_MAGMA_CUBE_SQUISH(new String[] { "MAGMACUBE_WALK", "ENTITY_MAGMACUBE_SQUISH" }),
/* 401 */   ENTITY_MAGMA_CUBE_SQUISH_SMALL(new String[] { "MAGMACUBE_WALK2", "ENTITY_SMALL_MAGMACUBE_SQUISH" }),
/* 402 */   ENTITY_MINECART_INSIDE(new String[] { "MINECART_INSIDE" }),
/* 403 */   ENTITY_MINECART_RIDING(new String[] { "MINECART_BASE" }),
/* 404 */   ENTITY_MOOSHROOM_SHEAR(new String[0]),
/* 405 */   ENTITY_MULE_AMBIENT(new String[0]),
/* 406 */   ENTITY_MULE_CHEST(new String[] { "ENTITY_MULE_AMBIENT" }),
/* 407 */   ENTITY_MULE_DEATH(new String[] { "ENTITY_MULE_AMBIENT" }),
/* 408 */   ENTITY_MULE_HURT(new String[] { "ENTITY_MULE_AMBIENT" }),
/* 409 */   ENTITY_PAINTING_BREAK(new String[0]),
/* 410 */   ENTITY_PAINTING_PLACE(new String[0]),
/* 411 */   ENTITY_PARROT_AMBIENT(new String[0]),
/* 412 */   ENTITY_PARROT_DEATH(new String[0]),
/* 413 */   ENTITY_PARROT_EAT(new String[0]),
/* 414 */   ENTITY_PARROT_FLY(new String[0]),
/* 415 */   ENTITY_PARROT_HURT(new String[0]),
/* 416 */   ENTITY_PARROT_IMITATE_BLAZE(new String[0]),
/* 417 */   ENTITY_PARROT_IMITATE_CREEPER(new String[0]),
/* 418 */   ENTITY_PARROT_IMITATE_DROWNED(new String[0]),
/* 419 */   ENTITY_PARROT_IMITATE_ELDER_GUARDIAN(new String[0]),
/* 420 */   ENTITY_PARROT_IMITATE_ENDERMAN(new String[0]),
/* 421 */   ENTITY_PARROT_IMITATE_ENDERMITE(new String[0]),
/* 422 */   ENTITY_PARROT_IMITATE_ENDER_DRAGON(new String[0]),
/* 423 */   ENTITY_PARROT_IMITATE_EVOKER(new String[0]),
/* 424 */   ENTITY_PARROT_IMITATE_GHAST(new String[0]),
/* 425 */   ENTITY_PARROT_IMITATE_HUSK(new String[0]),
/* 426 */   ENTITY_PARROT_IMITATE_ILLUSIONER(new String[0]),
/* 427 */   ENTITY_PARROT_IMITATE_MAGMA_CUBE(new String[0]),
/* 428 */   ENTITY_PARROT_IMITATE_PHANTOM(new String[0]),
/* 429 */   ENTITY_PARROT_IMITATE_POLAR_BEAR(new String[0]),
/* 430 */   ENTITY_PARROT_IMITATE_SHULKER(new String[0]),
/* 431 */   ENTITY_PARROT_IMITATE_SILVERFISH(new String[0]),
/* 432 */   ENTITY_PARROT_IMITATE_SKELETON(new String[0]),
/* 433 */   ENTITY_PARROT_IMITATE_SLIME(new String[0]),
/* 434 */   ENTITY_PARROT_IMITATE_SPIDER(new String[0]),
/* 435 */   ENTITY_PARROT_IMITATE_STRAY(new String[0]),
/* 436 */   ENTITY_PARROT_IMITATE_VEX(new String[0]),
/* 437 */   ENTITY_PARROT_IMITATE_VINDICATOR(new String[0]),
/* 438 */   ENTITY_PARROT_IMITATE_WITCH(new String[0]),
/* 439 */   ENTITY_PARROT_IMITATE_WITHER(new String[0]),
/* 440 */   ENTITY_PARROT_IMITATE_WITHER_SKELETON(new String[0]),
/* 441 */   ENTITY_PARROT_IMITATE_WOLF(new String[0]),
/* 442 */   ENTITY_PARROT_IMITATE_ZOMBIE(new String[0]),
/* 443 */   ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN(new String[0]),
/* 444 */   ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER(new String[0]),
/* 445 */   ENTITY_PARROT_STEP(new String[0]),
/* 446 */   ENTITY_PHANTOM_AMBIENT(new String[0]),
/* 447 */   ENTITY_PHANTOM_BITE(new String[0]),
/* 448 */   ENTITY_PHANTOM_DEATH(new String[0]),
/* 449 */   ENTITY_PHANTOM_FLAP(new String[0]),
/* 450 */   ENTITY_PHANTOM_HURT(new String[0]),
/* 451 */   ENTITY_PHANTOM_SWOOP(new String[0]),
/* 452 */   ENTITY_PIG_AMBIENT(new String[] { "PIG_IDLE" }),
/* 453 */   ENTITY_PIG_DEATH(new String[] { "PIG_DEATH" }),
/* 454 */   ENTITY_PIG_HURT(new String[0]),
/* 455 */   ENTITY_PIG_SADDLE(new String[] { "ENTITY_PIG_HURT" }),
/* 456 */   ENTITY_PIG_STEP(new String[] { "PIG_WALK" }),
/* 457 */   ENTITY_PLAYER_ATTACK_CRIT(new String[0]),
/* 458 */   ENTITY_PLAYER_ATTACK_KNOCKBACK(new String[0]),
/* 459 */   ENTITY_PLAYER_ATTACK_NODAMAGE(new String[0]),
/* 460 */   ENTITY_PLAYER_ATTACK_STRONG(new String[] { "SUCCESSFUL_HIT" }),
/* 461 */   ENTITY_PLAYER_ATTACK_SWEEP(new String[0]),
/* 462 */   ENTITY_PLAYER_ATTACK_WEAK(new String[0]),
/* 463 */   ENTITY_PLAYER_BIG_FALL(new String[] { "FALL_BIG" }),
/* 464 */   ENTITY_PLAYER_BREATH(new String[0]),
/* 465 */   ENTITY_PLAYER_BURP(new String[] { "BURP" }),
/* 466 */   ENTITY_PLAYER_DEATH(new String[0]),
/* 467 */   ENTITY_PLAYER_HURT(new String[] { "HURT_FLESH" }),
/* 468 */   ENTITY_PLAYER_HURT_DROWN(new String[0]),
/* 469 */   ENTITY_PLAYER_HURT_ON_FIRE(new String[0]),
/* 470 */   ENTITY_PLAYER_LEVELUP(new String[] { "LEVEL_UP" }),
/* 471 */   ENTITY_PLAYER_SMALL_FALL(new String[] { "FALL_SMALL" }),
/* 472 */   ENTITY_PLAYER_SPLASH(new String[] { "SLASH" }),
/* 473 */   ENTITY_PLAYER_SPLASH_HIGH_SPEED(new String[] { "SPLASH" }),
/* 474 */   ENTITY_PLAYER_SWIM(new String[] { "SWIM" }),
/* 475 */   ENTITY_POLAR_BEAR_AMBIENT(new String[0]),
/* 476 */   ENTITY_POLAR_BEAR_AMBIENT_BABY(new String[] { "ENTITY_POLAR_BEAR_BABY_AMBIENT" }),
/* 477 */   ENTITY_POLAR_BEAR_DEATH(new String[0]),
/* 478 */   ENTITY_POLAR_BEAR_HURT(new String[0]),
/* 479 */   ENTITY_POLAR_BEAR_STEP(new String[0]),
/* 480 */   ENTITY_POLAR_BEAR_WARNING(new String[0]),
/* 481 */   ENTITY_PUFFER_FISH_AMBIENT(new String[0]),
/* 482 */   ENTITY_PUFFER_FISH_BLOW_OUT(new String[0]),
/* 483 */   ENTITY_PUFFER_FISH_BLOW_UP(new String[0]),
/* 484 */   ENTITY_PUFFER_FISH_DEATH(new String[0]),
/* 485 */   ENTITY_PUFFER_FISH_FLOP(new String[0]),
/* 486 */   ENTITY_PUFFER_FISH_HURT(new String[0]),
/* 487 */   ENTITY_PUFFER_FISH_STING(new String[0]),
/* 488 */   ENTITY_RABBIT_AMBIENT(new String[0]),
/* 489 */   ENTITY_RABBIT_ATTACK(new String[0]),
/* 490 */   ENTITY_RABBIT_DEATH(new String[0]),
/* 491 */   ENTITY_RABBIT_HURT(new String[0]),
/* 492 */   ENTITY_RABBIT_JUMP(new String[0]),
/* 493 */   ENTITY_SALMON_AMBIENT(new String[0]),
/* 494 */   ENTITY_SALMON_DEATH(new String[0]),
/* 495 */   ENTITY_SALMON_FLOP(new String[0]),
/* 496 */   ENTITY_SALMON_HURT(new String[] { "ENTITY_SALMON_FLOP" }),
/* 497 */   ENTITY_SHEEP_AMBIENT(new String[] { "SHEEP_IDLE" }),
/* 498 */   ENTITY_SHEEP_DEATH(new String[0]),
/* 499 */   ENTITY_SHEEP_HURT(new String[0]),
/* 500 */   ENTITY_SHEEP_SHEAR(new String[] { "SHEEP_SHEAR" }),
/* 501 */   ENTITY_SHEEP_STEP(new String[] { "SHEEP_WALK" }),
/* 502 */   ENTITY_SHULKER_AMBIENT(new String[0]),
/* 503 */   ENTITY_SHULKER_BULLET_HIT(new String[0]),
/* 504 */   ENTITY_SHULKER_BULLET_HURT(new String[0]),
/* 505 */   ENTITY_SHULKER_CLOSE(new String[0]),
/* 506 */   ENTITY_SHULKER_DEATH(new String[0]),
/* 507 */   ENTITY_SHULKER_HURT(new String[0]),
/* 508 */   ENTITY_SHULKER_HURT_CLOSED(new String[0]),
/* 509 */   ENTITY_SHULKER_OPEN(new String[0]),
/* 510 */   ENTITY_SHULKER_SHOOT(new String[0]),
/* 511 */   ENTITY_SHULKER_TELEPORT(new String[0]),
/* 512 */   ENTITY_SILVERFISH_AMBIENT(new String[] { "SILVERFISH_IDLE" }),
/* 513 */   ENTITY_SILVERFISH_DEATH(new String[] { "SILVERFISH_KILL" }),
/* 514 */   ENTITY_SILVERFISH_HURT(new String[] { "SILVERFISH_HIT" }),
/* 515 */   ENTITY_SILVERFISH_STEP(new String[] { "SILVERFISH_WALK" }),
/* 516 */   ENTITY_SKELETON_AMBIENT(new String[] { "SKELETON_IDLE" }),
/* 517 */   ENTITY_SKELETON_DEATH(new String[] { "SKELETON_DEATH" }),
/* 518 */   ENTITY_SKELETON_HORSE_AMBIENT(new String[] { "HORSE_SKELETON_IDLE" }),
/* 519 */   ENTITY_SKELETON_HORSE_AMBIENT_WATER(new String[0]),
/* 520 */   ENTITY_SKELETON_HORSE_DEATH(new String[] { "HORSE_SKELETON_DEATH" }),
/* 521 */   ENTITY_SKELETON_HORSE_GALLOP_WATER(new String[0]),
/* 522 */   ENTITY_SKELETON_HORSE_HURT(new String[] { "HORSE_SKELETON_HIT" }),
/* 523 */   ENTITY_SKELETON_HORSE_JUMP_WATER(new String[0]),
/* 524 */   ENTITY_SKELETON_HORSE_STEP_WATER(new String[0]),
/* 525 */   ENTITY_SKELETON_HORSE_SWIM(new String[0]),
/* 526 */   ENTITY_SKELETON_HURT(new String[] { "SKELETON_HURT" }),
/* 527 */   ENTITY_SKELETON_SHOOT(new String[0]),
/* 528 */   ENTITY_SKELETON_STEP(new String[] { "SKELETON_WALK" }),
/* 529 */   ENTITY_SLIME_ATTACK(new String[] { "SLIME_ATTACK" }),
/* 530 */   ENTITY_SLIME_DEATH(new String[0]),
/* 531 */   ENTITY_SLIME_DEATH_SMALL(new String[0]),
/* 532 */   ENTITY_SLIME_HURT(new String[0]),
/* 533 */   ENTITY_SLIME_HURT_SMALL(new String[] { "ENTITY_SMALL_SLIME_HURT" }),
/* 534 */   ENTITY_SLIME_JUMP(new String[] { "SLIME_WALK" }),
/* 535 */   ENTITY_SLIME_JUMP_SMALL(new String[] { "SLIME_WALK2", "ENTITY_SMALL_SLIME_SQUISH" }),
/* 536 */   ENTITY_SLIME_SQUISH(new String[] { "SLIME_WALK2" }),
/* 537 */   ENTITY_SLIME_SQUISH_SMALL(new String[] { "ENTITY_SMALL_SLIME_SQUISH" }),
/* 538 */   ENTITY_SNOWBALL_THROW(new String[0]),
/* 539 */   ENTITY_SNOW_GOLEM_AMBIENT(new String[] { "ENTITY_SNOWMAN_AMBIENT" }),
/* 540 */   ENTITY_SNOW_GOLEM_DEATH(new String[] { "ENTITY_SNOWMAN_DEATH" }),
/* 541 */   ENTITY_SNOW_GOLEM_HURT(new String[] { "ENTITY_SNOWMAN_HURT" }),
/* 542 */   ENTITY_SNOW_GOLEM_SHOOT(new String[] { "ENTITY_SNOWMAN_SHOOT" }),
/* 543 */   ENTITY_SPIDER_AMBIENT(new String[] { "SPIDER_IDLE" }),
/* 544 */   ENTITY_SPIDER_DEATH(new String[] { "SPIDER_DEATH" }),
/* 545 */   ENTITY_SPIDER_HURT(new String[0]),
/* 546 */   ENTITY_SPIDER_STEP(new String[] { "SPIDER_WALK" }),
/* 547 */   ENTITY_SPLASH_POTION_BREAK(new String[0]),
/* 548 */   ENTITY_SPLASH_POTION_THROW(new String[0]),
/* 549 */   ENTITY_SQUID_AMBIENT(new String[0]),
/* 550 */   ENTITY_SQUID_DEATH(new String[0]),
/* 551 */   ENTITY_SQUID_HURT(new String[0]),
/* 552 */   ENTITY_SQUID_SQUIRT(new String[0]),
/* 553 */   ENTITY_STRAY_AMBIENT(new String[0]),
/* 554 */   ENTITY_STRAY_DEATH(new String[0]),
/* 555 */   ENTITY_STRAY_HURT(new String[0]),
/* 556 */   ENTITY_STRAY_STEP(new String[0]),
/* 557 */   ENTITY_TNT_PRIMED(new String[] { "FUSE" }),
/* 558 */   ENTITY_TROPICAL_FISH_AMBIENT(new String[0]),
/* 559 */   ENTITY_TROPICAL_FISH_DEATH(new String[0]),
/* 560 */   ENTITY_TROPICAL_FISH_FLOP(new String[] { "ENTITY_TROPICAL_FISH_DEATH" }),
/* 561 */   ENTITY_TROPICAL_FISH_HURT(new String[0]),
/* 562 */   ENTITY_TURTLE_AMBIENT_LAND(new String[0]),
/* 563 */   ENTITY_TURTLE_DEATH(new String[0]),
/* 564 */   ENTITY_TURTLE_DEATH_BABY(new String[0]),
/* 565 */   ENTITY_TURTLE_EGG_BREAK(new String[0]),
/* 566 */   ENTITY_TURTLE_EGG_CRACK(new String[0]),
/* 567 */   ENTITY_TURTLE_EGG_HATCH(new String[0]),
/* 568 */   ENTITY_TURTLE_HURT(new String[0]),
/* 569 */   ENTITY_TURTLE_HURT_BABY(new String[0]),
/* 570 */   ENTITY_TURTLE_LAY_EGG(new String[0]),
/* 571 */   ENTITY_TURTLE_SHAMBLE(new String[0]),
/* 572 */   ENTITY_TURTLE_SHAMBLE_BABY(new String[0]),
/* 573 */   ENTITY_TURTLE_SWIM(new String[0]),
/* 574 */   ENTITY_VEX_AMBIENT(new String[0]),
/* 575 */   ENTITY_VEX_CHARGE(new String[0]),
/* 576 */   ENTITY_VEX_DEATH(new String[0]),
/* 577 */   ENTITY_VEX_HURT(new String[0]),
/* 578 */   ENTITY_VILLAGER_AMBIENT(new String[] { "VILLAGER_IDLE" }),
/* 579 */   ENTITY_VILLAGER_DEATH(new String[] { "VILLAGER_DEATH" }),
/* 580 */   ENTITY_VILLAGER_HURT(new String[] { "VILLAGER_HIT" }),
/* 581 */   ENTITY_VILLAGER_NO(new String[] { "VILLAGER_NO" }),
/* 582 */   ENTITY_VILLAGER_TRADE(new String[] { "VILLAGER_HAGGLE", "ENTITY_VILLAGER_TRADING" }),
/* 583 */   ENTITY_VILLAGER_YES(new String[] { "VILLAGER_YES" }),
/* 584 */   ENTITY_VINDICATOR_AMBIENT(new String[] { "ENTITY_VINDICATION_ILLAGER_AMBIENT" }),
/* 585 */   ENTITY_VINDICATOR_DEATH(new String[] { "ENTITY_VINDICATION_ILLAGER_DEATH" }),
/* 586 */   ENTITY_VINDICATOR_HURT(new String[] { "ENTITY_VINDICATION_ILLAGER_HURT" }),
/* 587 */   ENTITY_WITCH_AMBIENT(new String[0]),
/* 588 */   ENTITY_WITCH_DEATH(new String[0]),
/* 589 */   ENTITY_WITCH_DRINK(new String[0]),
/* 590 */   ENTITY_WITCH_HURT(new String[0]),
/* 591 */   ENTITY_WITCH_THROW(new String[0]),
/* 592 */   ENTITY_WITHER_AMBIENT(new String[] { "WITHER_IDLE" }),
/* 593 */   ENTITY_WITHER_BREAK_BLOCK(new String[0]),
/* 594 */   ENTITY_WITHER_DEATH(new String[] { "WITHER_DEATH" }),
/* 595 */   ENTITY_WITHER_HURT(new String[] { "WITHER_HURT" }),
/* 596 */   ENTITY_WITHER_SHOOT(new String[] { "WITHER_SHOOT" }),
/* 597 */   ENTITY_WITHER_SKELETON_AMBIENT(new String[0]),
/* 598 */   ENTITY_WITHER_SKELETON_DEATH(new String[0]),
/* 599 */   ENTITY_WITHER_SKELETON_HURT(new String[0]),
/* 600 */   ENTITY_WITHER_SKELETON_STEP(new String[0]),
/* 601 */   ENTITY_WITHER_SPAWN(new String[] { "WITHER_SPAWN" }),
/* 602 */   ENTITY_WOLF_AMBIENT(new String[] { "WOLF_BARK" }),
/* 603 */   ENTITY_WOLF_DEATH(new String[] { "WOLF_DEATH" }),
/* 604 */   ENTITY_WOLF_GROWL(new String[] { "WOLF_GROWL" }),
/* 605 */   ENTITY_WOLF_HOWL(new String[] { "WOLF_HOWL" }),
/* 606 */   ENTITY_WOLF_HURT(new String[] { "WOLF_HURT" }),
/* 607 */   ENTITY_WOLF_PANT(new String[] { "WOLF_PANT" }),
/* 608 */   ENTITY_WOLF_SHAKE(new String[] { "WOLF_SHAKE" }),
/* 609 */   ENTITY_WOLF_STEP(new String[] { "WOLF_WALK" }),
/* 610 */   ENTITY_WOLF_WHINE(new String[] { "WOLF_WHINE" }),
/* 611 */   ENTITY_ZOMBIE_AMBIENT(new String[] { "ZOMBIE_IDLE" }),
/* 612 */   ENTITY_ZOMBIE_ATTACK_IRON_DOOR(new String[] { "ZOMBIE_METAL" }),
/* 613 */   ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR(new String[] { "ZOMBIE_WOOD", "ENTITY_ZOMBIE_ATTACK_DOOR_WOOD" }),
/* 614 */   ENTITY_ZOMBIE_BREAK_WOODEN_DOOR(new String[] { "ZOMBIE_WOODBREAK", "ENTITY_ZOMBIE_BREAK_DOOR_WOOD" }),
/* 615 */   ENTITY_ZOMBIE_CONVERTED_TO_DROWNED(new String[0]),
/* 616 */   ENTITY_ZOMBIE_DEATH(new String[] { "ZOMBIE_DEATH" }),
/* 617 */   ENTITY_ZOMBIE_DESTROY_EGG(new String[0]),
/* 618 */   ENTITY_ZOMBIE_HORSE_AMBIENT(new String[] { "HORSE_ZOMBIE_IDLE" }),
/* 619 */   ENTITY_ZOMBIE_HORSE_DEATH(new String[] { "HORSE_ZOMBIE_DEATH" }),
/* 620 */   ENTITY_ZOMBIE_HORSE_HURT(new String[] { "HORSE_ZOMBIE_HIT" }),
/* 621 */   ENTITY_ZOMBIE_HURT(new String[] { "ZOMBIE_HURT" }),
/* 622 */   ENTITY_ZOMBIE_INFECT(new String[] { "ZOMBIE_INFECT" }),
/* 623 */   ENTITY_ZOMBIE_PIGMAN_AMBIENT(new String[] { "ZOMBIE_PIG_IDLE", "ENTITY_ZOMBIE_PIG_AMBIENT" }),
/* 624 */   ENTITY_ZOMBIE_PIGMAN_ANGRY(new String[] { "ZOMBIE_PIG_ANGRY", "ENTITY_ZOMBIE_PIG_ANGRY" }),
/* 625 */   ENTITY_ZOMBIE_PIGMAN_DEATH(new String[] { "ZOMBIE_PIG_DEATH", "ENTITY_ZOMBIE_PIG_DEATH" }),
/* 626 */   ENTITY_ZOMBIE_PIGMAN_HURT(new String[] { "ZOMBIE_PIG_HURT", "ENTITY_ZOMBIE_PIG_HURT" }),
/* 627 */   ENTITY_ZOMBIE_STEP(new String[] { "ZOMBIE_WALK" }),
/* 628 */   ENTITY_ZOMBIE_VILLAGER_AMBIENT(new String[0]),
/* 629 */   ENTITY_ZOMBIE_VILLAGER_CONVERTED(new String[] { "ZOMBIE_UNFECT" }),
/* 630 */   ENTITY_ZOMBIE_VILLAGER_CURE(new String[] { "ZOMBIE_REMEDY" }),
/* 631 */   ENTITY_ZOMBIE_VILLAGER_DEATH(new String[0]),
/* 632 */   ENTITY_ZOMBIE_VILLAGER_HURT(new String[0]),
/* 633 */   ENTITY_ZOMBIE_VILLAGER_STEP(new String[0]),
/* 634 */   ITEM_ARMOR_EQUIP_CHAIN(new String[0]),
/* 635 */   ITEM_ARMOR_EQUIP_DIAMOND(new String[0]),
/* 636 */   ITEM_ARMOR_EQUIP_ELYTRA(new String[0]),
/* 637 */   ITEM_ARMOR_EQUIP_GENERIC(new String[0]),
/* 638 */   ITEM_ARMOR_EQUIP_GOLD(new String[0]),
/* 639 */   ITEM_ARMOR_EQUIP_IRON(new String[0]),
/* 640 */   ITEM_ARMOR_EQUIP_LEATHER(new String[0]),
/* 641 */   ITEM_ARMOR_EQUIP_TURTLE(new String[0]),
/* 642 */   ITEM_AXE_STRIP(new String[0]),
/* 643 */   ITEM_BOTTLE_EMPTY(new String[0]),
/* 644 */   ITEM_BOTTLE_FILL(new String[0]),
/* 645 */   ITEM_BOTTLE_FILL_DRAGONBREATH(new String[0]),
/* 646 */   ITEM_BUCKET_EMPTY(new String[0]),
/* 647 */   ITEM_BUCKET_EMPTY_FISH(new String[0]),
/* 648 */   ITEM_BUCKET_EMPTY_LAVA(new String[0]),
/* 649 */   ITEM_BUCKET_FILL(new String[0]),
/* 650 */   ITEM_BUCKET_FILL_FISH(new String[0]),
/* 651 */   ITEM_BUCKET_FILL_LAVA(new String[0]),
/* 652 */   ITEM_CHORUS_FRUIT_TELEPORT(new String[0]),
/* 653 */   ITEM_ELYTRA_FLYING(new String[0]),
/* 654 */   ITEM_FIRECHARGE_USE(new String[0]),
/* 655 */   ITEM_FLINTANDSTEEL_USE(new String[] { "FIRE_IGNITE" }),
/* 656 */   ITEM_HOE_TILL(new String[0]),
/* 657 */   ITEM_SHIELD_BLOCK(new String[0]),
/* 658 */   ITEM_SHIELD_BREAK(new String[0]),
/* 659 */   ITEM_SHOVEL_FLATTEN(new String[0]),
/* 660 */   ITEM_TOTEM_USE(new String[0]),
/* 661 */   ITEM_TRIDENT_HIT(new String[0]),
/* 662 */   ITEM_TRIDENT_HIT_GROUND(new String[0]),
/* 663 */   ITEM_TRIDENT_RETURN(new String[0]),
/* 664 */   ITEM_TRIDENT_RIPTIDE_1(new String[0]),
/* 665 */   ITEM_TRIDENT_RIPTIDE_2(new String[] { "ITEM_TRIDENT_RIPTIDE_1" }),
/* 666 */   ITEM_TRIDENT_RIPTIDE_3(new String[] { "ITEM_TRIDENT_RIPTIDE_1" }),
/* 667 */   ITEM_TRIDENT_THROW(new String[0]),
/* 668 */   ITEM_TRIDENT_THUNDER(new String[0]),
/* 669 */   MUSIC_CREATIVE(new String[0]),
/* 670 */   MUSIC_CREDITS(new String[0]),
/* 671 */   MUSIC_DISC_11(new String[] { "RECORD_11" }),
/* 672 */   MUSIC_DISC_13(new String[] { "RECORD_13" }),
/* 673 */   MUSIC_DISC_BLOCKS(new String[] { "RECORD_BLOCKS" }),
/* 674 */   MUSIC_DISC_CAT(new String[] { "RECORD_CAT" }),
/* 675 */   MUSIC_DISC_CHIRP(new String[] { "RECORD_CHIRP" }),
/* 676 */   MUSIC_DISC_FAR(new String[] { "RECORD_FAR" }),
/* 677 */   MUSIC_DISC_MALL(new String[] { "RECORD_MALL" }),
/* 678 */   MUSIC_DISC_MELLOHI(new String[] { "RECORD_MELLOHI" }),
/* 679 */   MUSIC_DISC_STAL(new String[] { "RECORD_STAL" }),
/* 680 */   MUSIC_DISC_STRAD(new String[] { "RECORD_STRAD" }),
/* 681 */   MUSIC_DISC_WAIT(new String[] { "RECORD_WAIT" }),
/* 682 */   MUSIC_DISC_WARD(new String[] { "RECORD_WARD" }),
/* 683 */   MUSIC_DRAGON(new String[0]),
/* 684 */   MUSIC_END(new String[0]),
/* 685 */   MUSIC_GAME(new String[0]),
/* 686 */   MUSIC_MENU(new String[0]),
/* 687 */   MUSIC_NETHER(new String[0]),
/* 688 */   MUSIC_UNDER_WATER(new String[0]),
/* 689 */   UI_BUTTON_CLICK(new String[] { "CLICK" }),
/* 690 */   UI_TOAST_CHALLENGE_COMPLETE(new String[0]),
/* 691 */   UI_TOAST_IN(new String[0]),
/* 692 */   UI_TOAST_OUT(new String[0]),
/* 693 */   WEATHER_RAIN(new String[] { "AMBIENCE_RAIN" }),
/* 694 */   WEATHER_RAIN_ABOVE(new String[0]);
/*     */   
/*     */   public static final XSound[] VALUES;
/*     */   
/*     */   private static final HashMap<XSound, Sound> CACHED_SEARCH;
/*     */   
/*     */   private final String[] legacy;
/*     */   
/*     */   static {
/* 697 */     VALUES = values();
/* 698 */     CACHED_SEARCH = new HashMap<>();
/*     */   }
/*     */   
/*     */   XSound(String... legacy) {
/* 702 */     this.legacy = legacy;
/*     */   }
/*     */   
/*     */   @Nonnull
/*     */   private static String format(@Nonnull String name) {
/* 713 */     return StringUtils.replace(StringUtils.replace(name.toUpperCase(), "MINECRAFT:", ""), "-", "_").trim()
/* 714 */       .replaceAll("\\s+", "_").replaceAll("\\d+", "").replaceAll("\\W+", "");
/*     */   }
/*     */   
/*     */   public static boolean contains(String name) {
/* 724 */     Validate.notEmpty(name, "Sound name cannot be null or empty");
/* 725 */     String formatted = format(name);
/* 726 */     return Arrays.<XSound>stream(VALUES).anyMatch(s -> s.name().equals(paramString));
/*     */   }
/*     */   
/*     */   @Nullable
/*     */   public static XSound matchXSound(@Nonnull String name) {
/* 737 */     return Arrays.<XSound>stream(VALUES).filter(s -> !(!s.name().equals(format(paramString)) && !s.matchAnyLegacy(paramString))).findFirst().orElse(null);
/*     */   }
/*     */   
/*     */   public static void playSoundFromString(@Nonnull Player player, @Nonnull String sound) {
/* 751 */     Validate.notNull(player, "Player cannot be null");
/* 752 */     Validate.notEmpty(sound, "Sound string cannot be null or empty");
/* 753 */     String[] split = StringUtils.replace(sound, " ", "").split(",");
/* 754 */     if (split.length == 0)
/* 755 */       throw new IllegalArgumentException("Sound string must at least have a sound name and must be separated with comma: " + sound); 
/*     */     try {
/*     */       float volume, pitch;
/* 758 */       String name = split[0];
/* 760 */       XSound xType = matchXSound(name);
/* 761 */       if (xType == null)
/* 762 */         throw new IllegalArgumentException("Invalid sound name: " + name); 
/* 763 */       Sound type = xType.parseSound();
/* 766 */       if (split.length == 2) {
/* 767 */         volume = Float.parseFloat(split[1]);
/*     */       } else {
/* 768 */         volume = 1.0F;
/*     */       } 
/* 770 */       if (split.length == 3) {
/* 771 */         pitch = Float.parseFloat(split[2]);
/*     */       } else {
/* 772 */         pitch = 0.0F;
/*     */       } 
/* 774 */       player.playSound(player.getLocation(), type, volume, pitch);
/* 775 */     } catch (NumberFormatException ex) {
/* 776 */       throw new NumberFormatException("There was a problem while getting a number for one of the sounds in config: " + ex.getMessage());
/* 777 */     } catch (IllegalArgumentException ex) {
/* 778 */       throw new IllegalArgumentException("There was a problem while getting a sound type in config: " + ex.getMessage());
/*     */     } 
/*     */   }
/*     */   
/*     */   @Nonnull
/*     */   public String[] getLegacy() {
/* 789 */     return this.legacy;
/*     */   }
/*     */   
/*     */   @Nullable
/*     */   public Sound parseSound() {
/* 799 */     Sound sound = CACHED_SEARCH.get(this);
/* 800 */     if (sound != null)
/* 800 */       return sound; 
/*     */     try {
/* 803 */       sound = Sound.valueOf(name());
/* 804 */     } catch (IllegalArgumentException ignored) {
/*     */       byte b;
/*     */       int i;
/*     */       String[] arrayOfString;
/* 805 */       for (i = (arrayOfString = this.legacy).length, b = 0; b < i; ) {
/* 805 */         String legacy = arrayOfString[b];
/*     */         try {
/* 807 */           sound = Sound.valueOf(legacy);
/* 808 */         } catch (IllegalArgumentException illegalArgumentException) {}
/*     */         b++;
/*     */       } 
/*     */     } 
/* 814 */     CACHED_SEARCH.put(this, sound);
/* 815 */     return sound;
/*     */   }
/*     */   
/*     */   public boolean matchAnyLegacy(@Nonnull String name) {
/* 825 */     name = format(name);
/* 826 */     return Arrays.<String>asList(this.legacy).contains(name);
/*     */   }
/*     */   
/*     */   public void playSound(@Nonnull Player player) {
/* 833 */     playSound(player, 1.0F, 1.0F);
/*     */   }
/*     */   
/*     */   public void playSound(@Nonnull Player player, float volume, float pitch) {
/* 844 */     Objects.requireNonNull(player, "Player cannot be null");
/* 845 */     if (player.isOnline())
/* 846 */       player.playSound(player.getLocation(), parseSound(), volume, pitch); 
/*     */   }
/*     */ }


/* Location:              C:\Users\Administrator\Desktop\FreeCoinFlip-Folia.jar!\sk\DexterSK\FreeCoinFli\\utilz\XSound.class
 * Java compiler version: 12 (56.0)
 * JD-Core Version:       1.1.3
 */